# Generated by Django 5.0.14 on 2026-03-31 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_unique_key_teacher_teacher_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClassStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='core.classschedule')),
            ],
            options={
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('daily_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.dailyclassstatus')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'unique_together': {('daily_class', 'student')},
            },
        ),
    ]
