# Generated by Django 5.0.14 on 2026-04-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dailyclassstatus_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
