# Generated by Django 5.0.14 on 2026-04-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='target_section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=1),
        ),
    ]
