# Generated by Django 5.0.14 on 2026-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_classschedule_target_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclassstatus',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailyclassstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
