import os
import django
from django.contrib.auth.hashers import make_password

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'college_connect.settings')
django.setup()

from core.models import Teacher, ClassSchedule, DailyClassStatus, Notification

def run():
    print("Initiating full reset of Teacher data...")
    # Flush existing data
    Teacher.objects.all().delete()
    print("Flushed old records.")

    main_teachers = [
        "Kirti Mathur",
        "Ramesh Thakur",
        "Shaligram Prajapat",
        "Yasmin Shaikh",
        "Rahul Singhai",
        "Jugendra Dongre",
        "Manju Suchdeo",
        "Poonam Mangwani",
        "Vivek Shrivastava",
        "Basant Namdeo",
        "Nitin Nagar",
        "Rupesh Sendre",
        "Shraddha Soni",
        "Kirti Vijayvargiya",
        "Rajesh Verma",
        "Pradeep K. Jatav",
        "Shailvi Verma",
        "Dheeraj Upadhyay"
    ]

    # Alphabetically sort the real teachers
    sorted_teachers = sorted(main_teachers)
    
    # Append the testing teachers explicitly at the absolute back
    sorted_teachers.append("Chinu Saxena")
    sorted_teachers.append("Deepak Bhatnagar")

    hashed_password = make_password("password123")
    
    print("\n--- NEW TEACHER ROSTER ---")
    generated_list = []
    
    for index, name in enumerate(sorted_teachers, start=1):
        # Strip all whitespace and punctuation, lowercase
        clean_name = ''.join(c for c in name if c.isalpha()).lower()
        # Add index suffix formatted to 2 digits (01, 02, etc.)
        username = f"{clean_name}{index:02d}"
        
        Teacher.objects.create(
            name=name,
            teacher_id=username,
            password=hashed_password
        )
        line = f"{index}. **{name}**\n   - Username: `{username}`"
        generated_list.append(line)
        print(f"{index}. {name} => {username}")
        
    # Write to local docs folder for portability
    docs_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'docs', 'faculty_credentials.md')
    with open(docs_path, "w", encoding='utf-8') as f:
        f.write("# Faculty Roster & Login Credentials\n\n")
        f.write("This list is automatically generated by `scripts/reset_roster.py`. The system-wide default password is **`password123`** for all accounts.\n\n")
        f.write("\n".join(generated_list))

    print("\nReset successfully completed and Artifact dynamically updated!")

if __name__ == '__main__':
    run()
